alg: rKD
comment: cifar
pretrain: True
pretrained_path: pretrained_CIFAR100_50_50.pth
arch: resnet18
# dataset related
dataset: cifar100
batch_size: 512
multicrop: True
num_large_crops: 2
num_small_crops: 2
num_labeled_classes: 80
num_unlabeled_classes: 20
save_model: True

# network
num_heads: 4
proj_dim: 256
hidden_dim: 2048
overcluster_factor: 4
num_hidden_layers: 1
feat_dim: 512

# learning 
lr: 0.4
min_lr: 0.001
warmup_epochs: 10
max_epochs: 500
momentum_opt: 0.9
weight_decay_opt: 1.5e-4
temperature: 0.1
kd_temperature: 4
num_workers: 10
num_iters_sk: 3
epsilon_sk: 0.05
# alpha: 0.02
amp: True